import { TabClass } from '@hms/basic/Index'
import TaskList from './TaskList'
import { TaskListParams, TaskListParamsModel, TaskTypeEnum } from '../../../models'

@Component
struct TaskTab {
  tabController: TabsController = new TabsController()
  @State
  tabsData: TabClass[] = [{
    name: 'waiting',
    title: '待提货'
  }, {
    name: 'line',
    title: '在途'
  }, {
    name: 'finish',
    title: '已完成'
  }]
  @State
  currentIndex: number = 0

  @Builder
  getTabBar(item: TabClass) {
    Column() {
      Text(item.title)
        .fontSize(16)
        .margin({
          bottom: 10
        })
        .animation({
          duration: 300
        })
        .fontWeight(this.tabsData[this.currentIndex].name === item.name ? 600 : FontWeight.Regular)
        .fontColor(this.tabsData[this.currentIndex].name === item.name ? $r("app.color.text_primary") : $r("app.color.text_secondary"))
      Divider()
        .strokeWidth(4)
        .width(this.tabsData[this.currentIndex].name === item.name ? 23 : 0)
        .color($r("app.color.primary"))
        .lineCap(LineCapStyle.Round)
        .animation({
          duration: 300
        })
    }
    .onClick(() => {
      // 通过name找到索引
      const index = this.tabsData.findIndex(obj => obj.name === item.name)
      this.tabController.changeIndex(index) // 切换索引
    })
  }

  build() {
    //
    Stack({ alignContent: Alignment.Top }) {
      Tabs({ index: $$this.currentIndex, controller: this.tabController }) {
        ForEach(this.tabsData, (item: TabClass) => {
          TabContent() {
            if (item.name === 'waiting') {
              TaskList()

            } else if (item.name === 'line') {
              TaskList({ queryParams: new TaskListParamsModel({
                page: 1,
                pageSize: 5,
                status: TaskTypeEnum.Line
              } as TaskListParams) })
            }
            else if (item.name === 'finish') {
              TaskList({ queryParams: new TaskListParamsModel({
                page: 1,
                pageSize: 5,
                status: TaskTypeEnum.Finish
              } as TaskListParams) })
            }
          }
        })
      }

      // 自定义渲染 盖住原有的内容
      Row({ space: 30 }) {
        // 有多少个就生成多少个页签
        ForEach(this.tabsData, (item: TabClass) => {
          this.getTabBar(item)
        })
      }
      .padding({
        left: 40,
        right: 40
      })
      .width("100%")
      .height(50)
      .backgroundColor($r("app.color.white"))
    }
  }
}
export default TaskTab